// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// blasso_2bg_vbeta_sigma2
Rcpp::List blasso_2bg_vbeta_sigma2(const arma::vec& vy, const arma::mat& mX, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const double& sigma2_init, const int& verbose);
RcppExport SEXP _LassoHiDFastGibbs_blasso_2bg_vbeta_sigma2(SEXP vySEXP, SEXP mXSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(blasso_2bg_vbeta_sigma2(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose));
    return rcpp_result_gen;
END_RCPP
}
// blasso_2bg_vbeta_lambda2
Rcpp::List blasso_2bg_vbeta_lambda2(const arma::vec& vy, const arma::mat& mX, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const double& sigma2_init, const arma::vec& va_init, const int& verbose, const double& lower, const double& upper);
RcppExport SEXP _LassoHiDFastGibbs_blasso_2bg_vbeta_lambda2(SEXP vySEXP, SEXP mXSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP va_initSEXP, SEXP verboseSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type va_init(va_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double& >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(blasso_2bg_vbeta_lambda2(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, va_init, verbose, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// lasso_gibbs_modified_hans
Rcpp::List lasso_gibbs_modified_hans(const arma::vec& vy, const arma::mat& mX, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const arma::vec& vbeta_init, const double& lambda_init, const double& sigma2_init, int verbose, bool tune_lambda2, bool rao_blackwellization);
RcppExport SEXP _LassoHiDFastGibbs_lasso_gibbs_modified_hans(SEXP vySEXP, SEXP mXSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP vbeta_initSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP verboseSEXP, SEXP tune_lambda2SEXP, SEXP rao_blackwellizationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vbeta_init(vbeta_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type tune_lambda2(tune_lambda2SEXP);
    Rcpp::traits::input_parameter< bool >::type rao_blackwellization(rao_blackwellizationSEXP);
    rcpp_result_gen = Rcpp::wrap(lasso_gibbs_modified_hans(vy, mX, a, b, u, v, nsamples, vbeta_init, lambda_init, sigma2_init, verbose, tune_lambda2, rao_blackwellization));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_4bg
Rcpp::List lm_penalized_4bg(const arma::vec& vy, const arma::mat& mX, const Rcpp::String penalty_type, const double& lambda_init, const double& sigma2_init, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const int& verbose);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_4bg(SEXP vySEXP, SEXP mXSEXP, SEXP penalty_typeSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_4bg(vy, mX, penalty_type, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_3bg
Rcpp::List lm_penalized_3bg(const arma::vec& vy, const arma::mat& mX, const Rcpp::String penalty_type, const double& lambda, const double& sigma2_init, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const int& verbose);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_3bg(SEXP vySEXP, SEXP mXSEXP, SEXP penalty_typeSEXP, SEXP lambdaSEXP, SEXP sigma2_initSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_3bg(vy, mX, penalty_type, lambda, sigma2_init, a, b, u, v, nsamples, verbose));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_nested_gibbs
Rcpp::List lm_penalized_nested_gibbs(const arma::vec& vy, const arma::mat& mX, const Rcpp::String penalty_type, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const arma::vec& va_init, const int& verbose, const double& lower, const double& upper, const int s_beta, const int s_siglam);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_nested_gibbs(SEXP vySEXP, SEXP mXSEXP, SEXP penalty_typeSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP va_initSEXP, SEXP verboseSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP s_betaSEXP, SEXP s_siglamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type va_init(va_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double& >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< const int >::type s_beta(s_betaSEXP);
    Rcpp::traits::input_parameter< const int >::type s_siglam(s_siglamSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_nested_gibbs(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper, s_beta, s_siglam));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_pcg_lambda2_col_sigma2
Rcpp::List lm_penalized_pcg_lambda2_col_sigma2(const arma::vec& vy, const arma::mat& mX, const Rcpp::String penalty_type, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const double& sigma2_init, const int& verbose);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_pcg_lambda2_col_sigma2(SEXP vySEXP, SEXP mXSEXP, SEXP penalty_typeSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_pcg_lambda2_col_sigma2(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_pcg_sigma2_col_lambda2
Rcpp::List lm_penalized_pcg_sigma2_col_lambda2(const arma::vec& vy, const arma::mat& mX, const Rcpp::String penalty_type, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const arma::vec& va_init, const int& verbose, const double& lower, const double& upper);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_lambda2(SEXP vySEXP, SEXP mXSEXP, SEXP penalty_typeSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP va_initSEXP, SEXP verboseSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type va_init(va_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double& >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_pcg_sigma2_col_lambda2(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// blasso_pcg_lambda2_col_va
Rcpp::List blasso_pcg_lambda2_col_va(const arma::vec& vy, const arma::mat& mX, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const double& sigma2_init, const int& verbose);
RcppExport SEXP _LassoHiDFastGibbs_blasso_pcg_lambda2_col_va(SEXP vySEXP, SEXP mXSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(blasso_pcg_lambda2_col_va(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_pcg_sigma2_col_va
Rcpp::List lm_penalized_pcg_sigma2_col_va(const arma::vec& vy, const arma::mat& mX, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const double& sigma2_init, const arma::vec& va_init, const int& verbose, const double& lower, const double& upper);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_va(SEXP vySEXP, SEXP mXSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP va_initSEXP, SEXP verboseSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type va_init(va_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double& >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_pcg_sigma2_col_va(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, va_init, verbose, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_pcg_vbeta_col_sigma2
Rcpp::List lm_penalized_pcg_vbeta_col_sigma2(const arma::vec& vy, const arma::mat& mX, const Rcpp::String penalty_type, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const double& sigma2_init, const int& verbose);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_pcg_vbeta_col_sigma2(SEXP vySEXP, SEXP mXSEXP, SEXP penalty_typeSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP sigma2_initSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const double& >::type sigma2_init(sigma2_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_pcg_vbeta_col_sigma2(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose));
    return rcpp_result_gen;
END_RCPP
}
// lm_penalized_pcg_sigma2_col_vbeta
Rcpp::List lm_penalized_pcg_sigma2_col_vbeta(const arma::vec& vy, const arma::mat& mX, const Rcpp::String penalty_type, const double& a, const double& b, const double& u, const double& v, const int& nsamples, const double& lambda_init, const arma::vec& va_init, const int& verbose, const double& lower, const double& upper);
RcppExport SEXP _LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_vbeta(SEXP vySEXP, SEXP mXSEXP, SEXP penalty_typeSEXP, SEXP aSEXP, SEXP bSEXP, SEXP uSEXP, SEXP vSEXP, SEXP nsamplesSEXP, SEXP lambda_initSEXP, SEXP va_initSEXP, SEXP verboseSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vy(vySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const Rcpp::String >::type penalty_type(penalty_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type a(aSEXP);
    Rcpp::traits::input_parameter< const double& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const double& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const double& >::type v(vSEXP);
    Rcpp::traits::input_parameter< const int& >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< const double& >::type lambda_init(lambda_initSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type va_init(va_initSEXP);
    Rcpp::traits::input_parameter< const int& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double& >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< const double& >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(lm_penalized_pcg_sigma2_col_vbeta(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// zetaOneLentz_c
double zetaOneLentz_c(double x, double tol, int maxiter);
RcppExport SEXP _LassoHiDFastGibbs_zetaOneLentz_c(SEXP xSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(zetaOneLentz_c(x, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LassoHiDFastGibbs_blasso_2bg_vbeta_sigma2", (DL_FUNC) &_LassoHiDFastGibbs_blasso_2bg_vbeta_sigma2, 10},
    {"_LassoHiDFastGibbs_blasso_2bg_vbeta_lambda2", (DL_FUNC) &_LassoHiDFastGibbs_blasso_2bg_vbeta_lambda2, 13},
    {"_LassoHiDFastGibbs_lasso_gibbs_modified_hans", (DL_FUNC) &_LassoHiDFastGibbs_lasso_gibbs_modified_hans, 13},
    {"_LassoHiDFastGibbs_lm_penalized_4bg", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_4bg, 11},
    {"_LassoHiDFastGibbs_lm_penalized_3bg", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_3bg, 11},
    {"_LassoHiDFastGibbs_lm_penalized_nested_gibbs", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_nested_gibbs, 15},
    {"_LassoHiDFastGibbs_lm_penalized_pcg_lambda2_col_sigma2", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_pcg_lambda2_col_sigma2, 11},
    {"_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_lambda2", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_lambda2, 13},
    {"_LassoHiDFastGibbs_blasso_pcg_lambda2_col_va", (DL_FUNC) &_LassoHiDFastGibbs_blasso_pcg_lambda2_col_va, 10},
    {"_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_va", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_va, 13},
    {"_LassoHiDFastGibbs_lm_penalized_pcg_vbeta_col_sigma2", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_pcg_vbeta_col_sigma2, 11},
    {"_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_vbeta", (DL_FUNC) &_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_vbeta, 13},
    {"_LassoHiDFastGibbs_zetaOneLentz_c", (DL_FUNC) &_LassoHiDFastGibbs_zetaOneLentz_c, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_LassoHiDFastGibbs(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
