# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blasso_2bg_vbeta_sigma2 <- function(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose = 1000L) {
    .Call(`_LassoHiDFastGibbs_blasso_2bg_vbeta_sigma2`, vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose)
}

blasso_2bg_vbeta_lambda2 <- function(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, va_init, verbose, lower, upper) {
    .Call(`_LassoHiDFastGibbs_blasso_2bg_vbeta_lambda2`, vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, va_init, verbose, lower, upper)
}

lasso_gibbs_modified_hans <- function(vy, mX, a, b, u, v, nsamples, vbeta_init, lambda_init, sigma2_init, verbose, tune_lambda2, rao_blackwellization) {
    .Call(`_LassoHiDFastGibbs_lasso_gibbs_modified_hans`, vy, mX, a, b, u, v, nsamples, vbeta_init, lambda_init, sigma2_init, verbose, tune_lambda2, rao_blackwellization)
}

lm_penalized_4bg <- function(vy, mX, penalty_type, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose = 10000L) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_4bg`, vy, mX, penalty_type, lambda_init, sigma2_init, a, b, u, v, nsamples, verbose)
}

lm_penalized_3bg <- function(vy, mX, penalty_type, lambda, sigma2_init, a, b, u, v, nsamples, verbose = 10000L) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_3bg`, vy, mX, penalty_type, lambda, sigma2_init, a, b, u, v, nsamples, verbose)
}

lm_penalized_nested_gibbs <- function(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper, s_beta = 1L, s_siglam = 1L) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_nested_gibbs`, vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper, s_beta, s_siglam)
}

lm_penalized_pcg_lambda2_col_sigma2 <- function(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose = 10000L) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_pcg_lambda2_col_sigma2`, vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose)
}

lm_penalized_pcg_sigma2_col_lambda2 <- function(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_lambda2`, vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper)
}

blasso_pcg_lambda2_col_va <- function(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose = 10000L) {
    .Call(`_LassoHiDFastGibbs_blasso_pcg_lambda2_col_va`, vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose)
}

lm_penalized_pcg_sigma2_col_va <- function(vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, va_init, verbose, lower, upper) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_va`, vy, mX, a, b, u, v, nsamples, lambda_init, sigma2_init, va_init, verbose, lower, upper)
}

lm_penalized_pcg_vbeta_col_sigma2 <- function(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose = 10000L) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_pcg_vbeta_col_sigma2`, vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, sigma2_init, verbose)
}

lm_penalized_pcg_sigma2_col_vbeta <- function(vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper) {
    .Call(`_LassoHiDFastGibbs_lm_penalized_pcg_sigma2_col_vbeta`, vy, mX, penalty_type, a, b, u, v, nsamples, lambda_init, va_init, verbose, lower, upper)
}

zetaOneLentz_c <- function(x, tol, maxiter) {
    .Call(`_LassoHiDFastGibbs_zetaOneLentz_c`, x, tol, maxiter)
}

